### PR TITLE
adds math/wrap

### PR DESCRIPTION
**Pull request by MathiasPaumgarten**
This method is both similar to `mout/math/loop` as well as the modulo operator. It allows to loop a number (overflow a number) over a certain range in both positive and negative values. 

It takes a value and a range [min, max). If no min is specified it assumes `0`. So when the number is larger than the upper bound, and no lower bound is given,`wrap( x, y )` will return the same value as `x % y`.

As for the PR, I had a hard time putting it into words, so, given we want to merge it, if someone could help me with the doc, that would be greatly appreciated. 

Let me know what you guys think.

### CODE REVIEW

**Comment by millermedeiros** [comment]
See #106! Exactly what I wanted.. What a coincidence

**Comment by MathiasPaumgarten** [comment]
I like the name `overflow` as it sounds like what it does. I chose `warp` based on image wrapping, which is similar to this and some people might be familiar with it from photoshop etc.

**Comment by millermedeiros** [comment]
:shipit: !

**Comment by millermedeiros** [comment]
check this out! http://stackoverflow.com/questions/707370/clean-efficient-algorithm-for-wrapping-integers-in-c

**Comment by MathiasPaumgarten** [comment]
@millermedeiros Thanks. I addressed this in 096ce432dbc117979b92397b84a6c8f2d852c325

**Pull request merged**
